
package com.concordfax;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FaxWSPortType", targetNamespace = "https://ws.concordfax.com/fax/v5/FaxWS.wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FaxWSPortType {


    /**
     * Service definition of function FaxWS__GetFaxAccountSettings
     * 
     * @param userID
     * @param accountInfo
     * @param wsError
     * @param strPIN
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GetFaxAccountSettings")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "GetFaxAccountSettings", targetNamespace = "urn:FaxWS", className = "com.concordfax.GetFaxAccountSettings")
    @ResponseWrapper(localName = "GetFaxAccountSettingsResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.GetFaxAccountSettingsResponse")
    public boolean getFaxAccountSettings(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "AccountInfo", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<ConcordAccount> accountInfo,
        @WebParam(name = "WSError", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<WSError> wsError);

    /**
     * Service definition of function FaxWS__CheckService
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CheckService")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "CheckService", targetNamespace = "urn:FaxWS", className = "com.concordfax.CheckService")
    @ResponseWrapper(localName = "CheckServiceResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.CheckServiceResponse")
    public String checkService();

    /**
     * Service definition of function FaxWS__SimpleSendFax
     * 
     * @param tiffJobFile
     * @param userID
     * @param faxNumber
     * @param recipientName
     * @param strPIN
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SimpleSendFax")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "SimpleSendFax", targetNamespace = "urn:FaxWS", className = "com.concordfax.SimpleSendFax")
    @ResponseWrapper(localName = "SimpleFaxSendResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.SimpleFaxSendResponse")
    public String simpleSendFax(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "RecipientName", targetNamespace = "urn:FaxWS")
        String recipientName,
        @WebParam(name = "FaxNumber", targetNamespace = "urn:FaxWS")
        String faxNumber,
        @WebParam(name = "TIFFJobFile", targetNamespace = "urn:FaxWS")
        byte[] tiffJobFile);

    /**
     * Service definition of function FaxWS__SimpleGetFaxStatus
     * 
     * @param userID
     * @param jobId
     * @param strPIN
     * @return
     *     returns long
     */
    @WebMethod(operationName = "SimpleGetFaxStatus")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "SimpleGetFaxStatus", targetNamespace = "urn:FaxWS", className = "com.concordfax.SimpleGetFaxStatus")
    @ResponseWrapper(localName = "SimpleFaxStatusResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.SimpleFaxStatusResponse")
    public long simpleGetFaxStatus(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "JobId", targetNamespace = "urn:FaxWS")
        String jobId);

    /**
     * Service definition of function FaxWS__SendFax
     * 
     * @param userID
     * @param faxJobIds
     * @param recipients
     * @param wsError
     * @param strPIN
     * @param faxJobFiles
     * @param ttfp
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SendFax")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "SendFax", targetNamespace = "urn:FaxWS", className = "com.concordfax.SendFax")
    @ResponseWrapper(localName = "FaxSendResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.FaxSendResponse")
    public boolean sendFax(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "Recipients", targetNamespace = "urn:FaxWS")
        FaxJobRecipients recipients,
        @WebParam(name = "FaxJobFiles", targetNamespace = "urn:FaxWS")
        FaxJobFiles faxJobFiles,
        @WebParam(name = "FaxJobIds", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<FaxJobIds> faxJobIds,
        @WebParam(name = "TTFP", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<Long> ttfp,
        @WebParam(name = "WSError", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<WSError> wsError);

    /**
     * Service definition of function FaxWS__SendFaxEx
     * 
     * @param jobDetails
     * @param userID
     * @param faxJobIds
     * @param recipients
     * @param wsError
     * @param strPIN
     * @param faxJobFiles
     * @param ttfp
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SendFaxEx")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "SendFaxEx", targetNamespace = "urn:FaxWS", className = "com.concordfax.SendFaxEx")
    @ResponseWrapper(localName = "FaxSendExResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.FaxSendExResponse")
    public boolean sendFaxEx(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "Recipients", targetNamespace = "urn:FaxWS")
        FaxJobRecipients recipients,
        @WebParam(name = "FaxJobFiles", targetNamespace = "urn:FaxWS")
        FaxJobFiles faxJobFiles,
        @WebParam(name = "JobDetails", targetNamespace = "urn:FaxWS")
        FaxJob jobDetails,
        @WebParam(name = "FaxJobIds", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<FaxJobIds> faxJobIds,
        @WebParam(name = "TTFP", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<Long> ttfp,
        @WebParam(name = "WSError", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<WSError> wsError);

    /**
     * Service definition of function FaxWS__SendFaxBroadcast
     * 
     * @param jobDetails
     * @param userID
     * @param faxJobId
     * @param recipients
     * @param wsError
     * @param strPIN
     * @param faxJobFiles
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SendFaxBroadcast")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "SendFaxBroadcast", targetNamespace = "urn:FaxWS", className = "com.concordfax.SendFaxBroadcast")
    @ResponseWrapper(localName = "FaxBroadcastResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.FaxBroadcastResponse")
    public boolean sendFaxBroadcast(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "Recipients", targetNamespace = "urn:FaxWS")
        FaxJobRecipients recipients,
        @WebParam(name = "FaxJobFiles", targetNamespace = "urn:FaxWS")
        FaxJobFiles faxJobFiles,
        @WebParam(name = "JobDetails", targetNamespace = "urn:FaxWS")
        FaxBroadcastJob jobDetails,
        @WebParam(name = "FaxJobId", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<String> faxJobId,
        @WebParam(name = "WSError", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<WSError> wsError);

    /**
     * Service definition of function FaxWS__SendFaxBroadcastEx
     * 
     * @param jobDetails
     * @param userID
     * @param faxJobId
     * @param csvFile
     * @param wsError
     * @param strPIN
     * @param faxJobFiles
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SendFaxBroadcastEx")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "SendFaxBroadcastEx", targetNamespace = "urn:FaxWS", className = "com.concordfax.SendFaxBroadcastEx")
    @ResponseWrapper(localName = "FaxBroadcastExResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.FaxBroadcastExResponse")
    public boolean sendFaxBroadcastEx(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "CSVFile", targetNamespace = "urn:FaxWS")
        byte[] csvFile,
        @WebParam(name = "FaxJobFiles", targetNamespace = "urn:FaxWS")
        FaxJobFiles faxJobFiles,
        @WebParam(name = "JobDetails", targetNamespace = "urn:FaxWS")
        FaxBroadcastJob jobDetails,
        @WebParam(name = "FaxJobId", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<String> faxJobId,
        @WebParam(name = "WSError", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<WSError> wsError);

    /**
     * Service definition of function FaxWS__GetFaxStatus
     * 
     * @param userID
     * @param faxStatusList
     * @param faxJobIds
     * @param wsError
     * @param strPIN
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GetFaxStatus")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "GetFaxStatus", targetNamespace = "urn:FaxWS", className = "com.concordfax.GetFaxStatus")
    @ResponseWrapper(localName = "FaxStatusResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.FaxStatusResponse")
    public boolean getFaxStatus(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "FaxJobIds", targetNamespace = "urn:FaxWS")
        FaxJobIds faxJobIds,
        @WebParam(name = "FaxStatusList", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<FaxStatusList> faxStatusList,
        @WebParam(name = "WSError", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<WSError> wsError);

    /**
     * Service definition of function FaxWS__GetRealTimeFaxStatus
     * 
     * @param userID
     * @param faxStatusList
     * @param faxJobIds
     * @param wsError
     * @param strPIN
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GetRealTimeFaxStatus")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "GetRealTimeFaxStatus", targetNamespace = "urn:FaxWS", className = "com.concordfax.GetRealTimeFaxStatus")
    @ResponseWrapper(localName = "RealTimeFaxStatusResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.RealTimeFaxStatusResponse")
    public boolean getRealTimeFaxStatus(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "FaxJobIds", targetNamespace = "urn:FaxWS")
        FaxJobIds faxJobIds,
        @WebParam(name = "FaxStatusList", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<RealTimeFaxStatusList> faxStatusList,
        @WebParam(name = "WSError", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<WSError> wsError);

    /**
     * Service definition of function FaxWS__GetRealTimeFaxStatusEx
     * 
     * @param userID
     * @param faxStatusList
     * @param faxJobIds
     * @param wsError
     * @param strPIN
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GetRealTimeFaxStatusEx")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "GetRealTimeFaxStatusEx", targetNamespace = "urn:FaxWS", className = "com.concordfax.GetRealTimeFaxStatusEx")
    @ResponseWrapper(localName = "RealTimeFaxStatusExResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.RealTimeFaxStatusExResponse")
    public boolean getRealTimeFaxStatusEx(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "FaxJobIds", targetNamespace = "urn:FaxWS")
        FaxJobIds faxJobIds,
        @WebParam(name = "FaxStatusList", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<RealTimeFaxStatusExList> faxStatusList,
        @WebParam(name = "WSError", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<WSError> wsError);

    /**
     * Service definition of function FaxWS__GetRealTimeFaxStatusEx2
     * 
     * @param userID
     * @param faxStatusList
     * @param faxJobIds
     * @param wsError
     * @param strPIN
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GetRealTimeFaxStatusEx2")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "GetRealTimeFaxStatusEx2", targetNamespace = "urn:FaxWS", className = "com.concordfax.GetRealTimeFaxStatusEx2")
    @ResponseWrapper(localName = "RealTimeFaxStatusEx2Response", targetNamespace = "urn:FaxWS", className = "com.concordfax.RealTimeFaxStatusEx2Response")
    public boolean getRealTimeFaxStatusEx2(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "FaxJobIds", targetNamespace = "urn:FaxWS")
        FaxJobIds faxJobIds,
        @WebParam(name = "FaxStatusList", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<RealTimeFaxStatusEx2List> faxStatusList,
        @WebParam(name = "WSError", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<WSError> wsError);

    /**
     * Service definition of function FaxWS__GetFaxBroadcastReport
     * 
     * @param userID
     * @param jobId
     * @param recipAddress
     * @param wsError
     * @param strPIN
     * @param recipientType
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GetFaxBroadcastReport")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "GetFaxBroadcastReport", targetNamespace = "urn:FaxWS", className = "com.concordfax.GetFaxBroadcastReport")
    @ResponseWrapper(localName = "GetFaxBroadcastReportResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.GetFaxBroadcastReportResponse")
    public boolean getFaxBroadcastReport(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "JobId", targetNamespace = "urn:FaxWS")
        String jobId,
        @WebParam(name = "RecipientType", targetNamespace = "urn:FaxWS")
        int recipientType,
        @WebParam(name = "RecipAddress", targetNamespace = "urn:FaxWS")
        String recipAddress,
        @WebParam(name = "WSError", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<WSError> wsError);

    /**
     * Service definition of function FaxWS__CancelFax
     * 
     * @param userID
     * @param jobId
     * @param wsError
     * @param strPIN
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CancelFax")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "CancelFax", targetNamespace = "urn:FaxWS", className = "com.concordfax.CancelFax")
    @ResponseWrapper(localName = "CancelFaxResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.CancelFaxResponse")
    public boolean cancelFax(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "JobId", targetNamespace = "urn:FaxWS")
        String jobId,
        @WebParam(name = "WSError", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<WSError> wsError);

    /**
     * Service definition of function FaxWS__GetFaxCoverList
     * 
     * @param faxCoverList
     * @param userID
     * @param wsError
     * @param strPIN
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GetFaxCoverList")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "GetFaxCoverList", targetNamespace = "urn:FaxWS", className = "com.concordfax.GetFaxCoverList")
    @ResponseWrapper(localName = "FaxCoverResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.FaxCoverResponse")
    public boolean getFaxCoverList(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "FaxCoverList", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<FaxCoverList> faxCoverList,
        @WebParam(name = "WSError", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<WSError> wsError);

    /**
     * Service definition of function FaxWS__GetFaxBroadcastStatus
     * 
     * @param userID
     * @param recipientStatusList
     * @param request
     * @param wsError
     * @param strPIN
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GetFaxBroadcastStatus")
    @WebResult(targetNamespace = "urn:FaxWS")
    @RequestWrapper(localName = "GetFaxBroadcastStatus", targetNamespace = "urn:FaxWS", className = "com.concordfax.GetFaxBroadcastStatus")
    @ResponseWrapper(localName = "FaxBroadcastStatusResponse", targetNamespace = "urn:FaxWS", className = "com.concordfax.FaxBroadcastStatusResponse")
    public boolean getFaxBroadcastStatus(
        @WebParam(name = "UserID", targetNamespace = "urn:FaxWS")
        String userID,
        @WebParam(name = "strPIN", targetNamespace = "urn:FaxWS")
        String strPIN,
        @WebParam(name = "request", targetNamespace = "urn:FaxWS")
        FaxBroadcastStatusRequest request,
        @WebParam(name = "RecipientStatusList", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<RecipientStatusList> recipientStatusList,
        @WebParam(name = "WSError", targetNamespace = "urn:FaxWS", mode = WebParam.Mode.OUT)
        Holder<WSError> wsError);

}
