
package com.concordfax;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * gSOAP 2.7.6c generated service definition
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FaxWS", targetNamespace = "https://ws.concordfax.com/fax/v5/FaxWS.wsdl", wsdlLocation = "https://ws.concordfax.com/fax/v5/faxws.wsdl")
public class FaxWS
    extends Service
{

    private final static URL FAXWS_WSDL_LOCATION;
    private final static WebServiceException FAXWS_EXCEPTION;
    private final static QName FAXWS_QNAME = new QName("https://ws.concordfax.com/fax/v5/FaxWS.wsdl", "FaxWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ws.concordfax.com/fax/v5/faxws.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FAXWS_WSDL_LOCATION = url;
        FAXWS_EXCEPTION = e;
    }

    public FaxWS() {
        super(__getWsdlLocation(), FAXWS_QNAME);
    }

    public FaxWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), FAXWS_QNAME, features);
    }

    public FaxWS(URL wsdlLocation) {
        super(wsdlLocation, FAXWS_QNAME);
    }

    public FaxWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FAXWS_QNAME, features);
    }

    public FaxWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FaxWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FaxWSPortType
     */
    @WebEndpoint(name = "FaxWS")
    public FaxWSPortType getFaxWS() {
        return super.getPort(new QName("https://ws.concordfax.com/fax/v5/FaxWS.wsdl", "FaxWS"), FaxWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FaxWSPortType
     */
    @WebEndpoint(name = "FaxWS")
    public FaxWSPortType getFaxWS(WebServiceFeature... features) {
        return super.getPort(new QName("https://ws.concordfax.com/fax/v5/FaxWS.wsdl", "FaxWS"), FaxWSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FAXWS_EXCEPTION!= null) {
            throw FAXWS_EXCEPTION;
        }
        return FAXWS_WSDL_LOCATION;
    }

}
